service: nutshell-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-2
  httpApi:
    cors: true

functions:
  testFunction:
    handler: index.hello
    events:
      - httpApi:
          path: /test
          method: get
  articleFetcher:
    handler: src/functions/articleFetcher.handler
    events:
      - httpApi:
          path: /fetch-article
          method: post