service: nutshell-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-2
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  httpApi:
    cors: true

functions:
  testFunction:
    handler: index.hello
    events:
      - httpApi:
          path: /test
          method: get
  articleFetcher:
    handler: src/articleFetcher.handler
    events:
      - httpApi:
          path: /fetch-article
          method: post
  summaryGenerator:
    handler: src/summaryGenerator.handler
    events:
      - httpApi:
          path: /summarise
          method: post