service: nutshell-server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-2
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    MONGO_URI: ${env:MONGO_URI}
    SECRET: ${env:SECRET}
  httpApi:
    cors: true

functions:
  testFunction:
    handler: index.hello
    events:
      - httpApi:
          path: /test
          method: get
  articleFetcher:
    handler: src/articleFetcher.handler
    events:
      - httpApi:
          path: /fetch-article
          method: post
  summaryGenerator:
    handler: src/summaryGenerator.handler
    events:
      - httpApi:
          path: /summarise
          method: post
  mainHandler:
    handler: src/mainHandler.handler
    events:
      - httpApi:
          path: /handleRequest
          method: post
  app:
    handler: handler.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
